# Copyright (c) 2003-2015 Hans Ewetz (hansewetz at hotmail dot com)
# Distributed under the Boost Software License, Version 1.0. 

SUBDIRS = test1-type-utils test1-occi-tools test1-tpool test1-stopwatch test-boost-asio-qextensions

include $(PROJECT_ROOT)/makerules/subdirs.rules

