# Copyright (c) 2003-2015 Hans Ewetz (hansewetz at hotmail dot com)
# Distributed under the Boost Software License, Version 1.0. 

# To be built
LOCAL_TARGET    = test1-stopwatch
LOCAL_SOTARGET  =
LOCAL_OBJS      = test1-stopwatch.o

# Control.
LOCAL_LIBS      = -lboost_chrono
LOCAL_LIBPATH   = 
LOCAL_INCPATH   =-I$(ENV_ROOT)/include  -L${BOOST_LIB} -I${BOOST_INC} 
LOCAL_DEFINES   = 
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  =
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =

include $(ENV_ROOT)/makerules/build.rules

