# To be built
LOCAL_TARGET    = $(ENV_ROOT)/bin/test1-occi-tools
LOCAL_SOTARGET  = 
LOCAL_OBJS      = test1-occi-tools.o

# Control.
LOCAL_LIBS      = -locci -lclntsh -lociei -lnnz11
LOCAL_LIBPATH   = -L${OCCI_LIB}
LOCAL_INCPATH   = -I${OCCI_INC} -I$(ENV_ROOT)/include
LOCAL_DEFINES   =
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  =
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =

include $(ENV_ROOT)/makerules/build.rules
