# Copyright (c) 2003-2015 Hans Ewetz (hansewetz at hotmail dot com)
# Distributed under the Boost Software License, Version 1.0. 

# To be built
LOCAL_TARGET    = test1-occi-tools
LOCAL_SOTARGET  = 
LOCAL_OBJS      = test1-occi-tools.o

# Control.
LOCAL_LIBS      = -locci -lclntsh -lociei -lnnz11
LOCAL_LIBPATH   = -L${OCCI_LIB}
LOCAL_INCPATH   = -I${OCCI_INC} -I$(PROJECT_ROOT)/include
LOCAL_DEFINES   =
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  =
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =

include $(PROJECT_ROOT)/makerules/build.rules
