# Copyright (c) 2003-2015 Hans Ewetz (hansewetz at hotmail dot com)
# Distributed under the Boost Software License, Version 1.0. 

all:
	make -f Makefile.serv
	make -f Makefile.client

clean:
	make -f Makefile.serv clean
	make -f Makefile.client clean
