# To be built
LOCAL_TARGET    = ${ENV_ROOT}/bin/test1-stopwatch
LOCAL_SOTARGET  =
LOCAL_OBJS      = test1-stopwatch.o

# Control.
LOCAL_LIBS      = -lboost_chrono
LOCAL_LIBPATH   = 
LOCAL_INCPATH   =-I$(ENV_ROOT)/include  -L${BOOST_LIB} -I${BOOST_INC} 
LOCAL_DEFINES   = 
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  =
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =

include $(ENV_ROOT)/makerules/build.rules

