# Copyright (c) 2003-2015 Hans Ewetz (hansewetz at hotmail dot com)
# Distributed under the Boost Software License, Version 1.0. 

SUBDIRS = type-utils occi-tools general-tools boost-asio-queue-extension

include $(ENV_ROOT)/makerules/subdirs.rules

