# Copyright (c) 2003-2015 Hans Ewetz (hansewetz at hotmail dot com)
# Distributed under the Boost Software License, Version 1.0. 

SUBDIRS = test-10 test-11 test-2 test-3 test-33 test-4 test-5 test-55 test-6 test-7 test-8 test-9 test-simpleq1 test-simpleq2 test-simpleq3

include $(PROJECT_ROOT)/makerules/subdirs.rules

