# Copyright (c) 2003-2015 Hans Ewetz (hansewetz at hotmail dot com)
# Distributed under the Boost Software License, Version 1.0. 

SUBDIRS = libs tests

include $(PROJECT_ROOT)/makerules/subdirs.rules

libs: tests
